# Generated by Django 5.2.11 on 2026-03-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(help_text='Код валюты ISO 4217 (например: RUB, USD, CNY)', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название валюты (например: Российский рубль)', max_length=64)),
                ('symbol', models.CharField(blank=True, default='', help_text='Символ валюты (₽, $, ¥). Не обязателен.', max_length=8)),
                ('is_active', models.BooleanField(default=True, help_text='Можно ли выбирать эту валюту в новых документах')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'indexes': [models.Index(fields=['is_active'], name='finance_cur_is_acti_7c20ee_idx')],
            },
        ),
    ]
