# Generated by Django 5.2.11 on 2026-03-03 09:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(help_text='Название бренда (используется как ключ)', max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(help_text='Название категории (используется как ключ)', max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_code', models.CharField(max_length=3, unique=True)),
                ('inn', models.CharField(blank=True, default='', max_length=12)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('note', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectorCheckpoint',
            fields=[
                ('projector_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('last_occurred_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_id', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(max_length=50)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('aggregate_version', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=100)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payload', models.JSONField()),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['aggregate_type', 'aggregate_id', 'aggregate_version'], name='orders_even_aggrega_a959fa_idx'), models.Index(fields=['event_type', 'occurred_at'], name='orders_even_event_t_a71873_idx')],
                'constraints': [models.UniqueConstraint(fields=('aggregate_type', 'aggregate_id', 'aggregate_version'), name='uniq_stream_version')],
            },
        ),
        migrations.CreateModel(
            name='OrderItemView',
            fields=[
                ('item_id', models.UUIDField(primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(db_index=True)),
                ('product_barcode', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('planned_product_id', models.UUIDField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('production_days', models.IntegerField(default=0)),
                ('delivery_days', models.IntegerField(default=14)),
                ('planned_fx_to_rub', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['order_id', 'is_removed'], name='orders_orde_order_i_de9956_idx'), models.Index(fields=['product_barcode'], name='orders_orde_product_1abec6_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderView',
            fields=[
                ('order_id', models.UUIDField(primary_key=True, serialize=False)),
                ('human_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('buyer_commission_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('buyer_commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('buyer_delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('items_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_views', to='finance.currency')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_business_unit_views', to='orders.partner')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_buyer_views', to='orders.partner')),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='partners', to='orders.partnerrole'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('wb_sku', models.CharField(help_text='Уникальный Артикул WB', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('seller_sku', models.CharField(help_text='Артикул продавца, Название товара', max_length=255)),
                ('brand', models.ForeignKey(help_text='Бренд товара', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.brand')),
                ('category', models.ForeignKey(help_text='Категория товара', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.category')),
                ('partner', models.ForeignKey(blank=True, help_text='Владелец товара (клиент или Business Unit ИП Никита Край)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='orders.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название планового товара (придуманное нами)', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Фото планового товара (если есть)', null=True, upload_to='planned_products/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи')),
                ('linked_product', models.OneToOneField(blank=True, help_text='Реальный товар, с которым связали данный плановый товар', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_match', to='orders.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('barcode', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('tech_size', models.CharField(max_length=255)),
                ('wb_size', models.CharField(max_length=255)),
                ('color', models.CharField(default='', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='orders.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('human_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('buyer_commission_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('buyer_commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('buyer_delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_business_unit', to='orders.partner')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_buyer', to='orders.partner')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='finance.currency')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerMarketplaceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('wb', 'Wildberries'), ('ozon', 'Ozon'), ('ym', 'Yandex Market')], help_text='Маркетплейс', max_length=16)),
                ('token_name', models.CharField(help_text='Название токена (например statistics, analytics, orders_api)', max_length=64)),
                ('token_value', models.CharField(blank=True, default='', help_text='Значение токена', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли токен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_tokens', to='orders.partner')),
            ],
            options={
                'indexes': [models.Index(fields=['partner'], name='orders_part_partner_2ce56e_idx'), models.Index(fields=['partner', 'marketplace'], name='orders_part_partner_f4061c_idx'), models.Index(fields=['partner', 'marketplace', 'token_name'], name='orders_part_partner_c0e962_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('linked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='orders.plannedproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_links', to='orders.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan_product',), name='uniq_plan_product_once')],
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('big', 'Big'), ('c246x328', 'C246x328'), ('c516x688', 'C516x688'), ('hq', 'HQ'), ('square', 'Square'), ('tm', 'TM')], max_length=20)),
                ('url', models.URLField()),
                ('local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='orders.product')),
            ],
            options={
                'unique_together': {('product', 'photo_type')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('production_days', models.IntegerField(default=0)),
                ('delivery_days', models.IntegerField(default=14)),
                ('planned_fx_to_rub', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('planned_product', models.ForeignKey(blank=True, help_text='Плановый товар, который позже будет сопоставлен с баркодом', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.plannedproduct')),
                ('product_sku', models.ForeignKey(blank=True, help_text='Конкретный вариант товара по баркоду', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.productsku')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.purchaseorder')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('product_sku__isnull', False), ('planned_product__isnull', True)), models.Q(('product_sku__isnull', True), ('planned_product__isnull', False)), _connector='OR'), name='order_item_exactly_one_product_ref')],
            },
        ),
    ]
