# Generated by Django 5.2.11 on 2026-02-20 17:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderView',
            fields=[
                ('order_id', models.UUIDField(primary_key=True, serialize=False)),
                ('supplier_id', models.CharField(max_length=100)),
                ('order_currency', models.CharField(max_length=3)),
                ('base_currency', models.CharField(default='RUB', max_length=3)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectorCheckpoint',
            fields=[
                ('projector_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('last_occurred_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_id', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(max_length=50)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('aggregate_version', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=100)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payload', models.JSONField()),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['aggregate_type', 'aggregate_id', 'aggregate_version'], name='orders_even_aggrega_a959fa_idx'), models.Index(fields=['event_type', 'occurred_at'], name='orders_even_event_t_a71873_idx')],
                'constraints': [models.UniqueConstraint(fields=('aggregate_type', 'aggregate_id', 'aggregate_version'), name='uniq_stream_version')],
            },
        ),
    ]
