# Generated by Django 5.2.11 on 2026-03-17 12:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_code', models.CharField(max_length=3, unique=True)),
                ('inn', models.CharField(blank=True, default='', max_length=12)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('note', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Business Unit',
                'verbose_name_plural': 'Business Units',
            },
        ),
        migrations.CreateModel(
            name='BusinessUnitMarketplaceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marketplace', models.CharField(choices=[('wb', 'Wildberries'), ('ozon', 'Ozon'), ('ym', 'Yandex Market')], max_length=20)),
                ('token_name', models.CharField(default='default', help_text='Имя токена внутри маркетплейса, если у одного BU может быть несколько токенов', max_length=100)),
                ('token_value', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Unit Marketplace Token',
                'verbose_name_plural': 'Business Unit Marketplace Tokens',
            },
        ),
        migrations.CreateModel(
            name='OrderNumberCounter',
            fields=[
                ('prefix', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Счётчик номера заказа',
                'verbose_name_plural': 'Счётчики номеров заказов',
            },
        ),
        migrations.CreateModel(
            name='UserBusinessUnitAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User Business Unit Access',
                'verbose_name_plural': 'User Business Unit Accesses',
            },
        ),
        migrations.RemoveField(
            model_name='partnermarketplacetoken',
            name='partner',
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='orderitemview',
            options={'verbose_name': 'Order Item View', 'verbose_name_plural': 'Order Item Views'},
        ),
        migrations.AlterModelOptions(
            name='orderview',
            options={'verbose_name': 'Order View', 'verbose_name_plural': 'Order Views'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='partnerrole',
            options={'verbose_name': 'Partner Role', 'verbose_name_plural': 'Partner Roles'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='order_item_exactly_one_product_ref',
        ),
        migrations.AlterField(
            model_name='orderview',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_views_as_buyer', to='orders.partner'),
        ),
        migrations.AlterField(
            model_name='orderview',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_views', to='finance.currency'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_as_buyer', to='orders.partner'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='finance.currency'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['is_active'], name='orders_part_is_acti_41bf63_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['short_code'], name='orders_part_short_c_119698_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product_sku__isnull', False), ('planned_product__isnull', True)), models.Q(('product_sku__isnull', True), ('planned_product__isnull', False)), _connector='OR'), name='order_item_exactly_one_product_ref_barcode'),
        ),
        migrations.AddIndex(
            model_name='businessunit',
            index=models.Index(fields=['is_active'], name='orders_busi_is_acti_e48f40_idx'),
        ),
        migrations.AddIndex(
            model_name='businessunit',
            index=models.Index(fields=['short_code'], name='orders_busi_short_c_4d9900_idx'),
        ),
        migrations.AlterField(
            model_name='orderview',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_views', to='orders.businessunit'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.businessunit'),
        ),
        migrations.AddIndex(
            model_name='orderview',
            index=models.Index(fields=['human_code'], name='orders_orde_human_c_e92649_idx'),
        ),
        migrations.AddIndex(
            model_name='orderview',
            index=models.Index(fields=['status', 'date'], name='orders_orde_status_cbf3e5_idx'),
        ),
        migrations.AddIndex(
            model_name='orderview',
            index=models.Index(fields=['business_unit', 'buyer'], name='orders_orde_busines_deb9d2_idx'),
        ),
        migrations.AddField(
            model_name='businessunitmarketplacetoken',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_tokens', to='orders.businessunit'),
        ),
        migrations.AddField(
            model_name='userbusinessunitaccess',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='orders.businessunit'),
        ),
        migrations.AddField(
            model_name='userbusinessunitaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_unit_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PartnerMarketplaceToken',
        ),
        migrations.AddIndex(
            model_name='businessunitmarketplacetoken',
            index=models.Index(fields=['marketplace', 'is_active'], name='orders_busi_marketp_bedcb0_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessunitmarketplacetoken',
            constraint=models.UniqueConstraint(fields=('business_unit', 'marketplace', 'token_name'), name='uniq_bu_marketplace_token_name'),
        ),
        migrations.AddIndex(
            model_name='userbusinessunitaccess',
            index=models.Index(fields=['user', 'is_active'], name='orders_user_user_id_dfd4bf_idx'),
        ),
        migrations.AddIndex(
            model_name='userbusinessunitaccess',
            index=models.Index(fields=['business_unit', 'is_active'], name='orders_user_busines_b37627_idx'),
        ),
        migrations.AddConstraint(
            model_name='userbusinessunitaccess',
            constraint=models.UniqueConstraint(fields=('user', 'business_unit'), name='uniq_user_business_unit_access'),
        ),
    ]
