# Generated by Django 5.2.11 on 2026-03-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberCounter',
            fields=[
                ('prefix', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Счётчик номера заказа',
                'verbose_name_plural': 'Счётчики номеров заказов',
            },
        ),
    ]
