# Generated by ChatGPT on 2026-02-26

import uuid

from django.db import migrations, models
import django.db.models.deletion


def forwards_migrate_suppliers(apps, schema_editor):
    Supplier = apps.get_model("orders", "Supplier")
    Partner = apps.get_model("orders", "Partner")
    PartnerRole = apps.get_model("orders", "PartnerRole")

    supplier_role, _ = PartnerRole.objects.get_or_create(
        code="supplier",
        defaults={"title": "Supplier"},
    )

    # Переносим всех Supplier -> Partner с тем же UUID (чтобы FK сохранились)
    for s in Supplier.objects.all():
        # short_code обязателен и уникален: зададим детерминированный код из UUID
        sc = (s.id.hex[:3]).upper()  # 1–3 символа A-Z/0-9
        # На случай невероятной коллизии на первых 3 символах, сдвигаем окно
        i = 0
        while Partner.objects.filter(short_code=sc).exists():
            i += 1
            sc = (s.id.hex[i:i+3] or s.id.hex[:3]).upper()

        p, created = Partner.objects.get_or_create(
            id=s.id,
            defaults={
                "name": s.name,
                "short_code": sc,
                "phone": s.phone,
                "address": s.address,
                "note": s.note,
                "is_active": s.is_active,
                "inn": "",
                "email": "",
            },
        )
        # Если вдруг Partner уже существовал (редко), обновим базовые поля
        if not created:
            p.name = s.name
            p.phone = s.phone
            p.address = s.address
            p.note = s.note
            p.is_active = s.is_active
            p.save(update_fields=["name", "phone", "address", "note", "is_active"])

        p.roles.add(supplier_role)


def backwards_restore_suppliers(apps, schema_editor):
    # Обратная миграция: восстановить Supplier из Partner с ролью supplier
    Supplier = apps.get_model("orders", "Supplier")
    Partner = apps.get_model("orders", "Partner")
    PartnerRole = apps.get_model("orders", "PartnerRole")

    try:
        supplier_role = PartnerRole.objects.get(code="supplier")
    except PartnerRole.DoesNotExist:
        return

    qs = Partner.objects.filter(roles=supplier_role)
    for p in qs:
        Supplier.objects.get_or_create(
            id=p.id,
            defaults={
                "name": p.name,
                "phone": p.phone,
                "address": p.address,
                "note": p.note,
                "is_active": p.is_active,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_supplier_remove_orderview_supplier_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=32, unique=True)),
                ("title", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("short_code", models.CharField(max_length=3, unique=True)),
                ("inn", models.CharField(blank=True, default="", max_length=12)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("address", models.CharField(blank=True, default="", max_length=300)),
                ("note", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="partner",
            name="roles",
            field=models.ManyToManyField(blank=True, related_name="partners", to="orders.partnerrole"),
        ),
        migrations.RunPython(forwards_migrate_suppliers, backwards_restore_suppliers),
        migrations.AlterField(
            model_name="orderview",
            name="supplier",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orders_as_supplier", to="orders.partner"),
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
