# Generated by Django 5.2.11 on 2026-02-26 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_partner_roles_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerMarketplaceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('wb', 'Wildberries'), ('ozon', 'Ozon'), ('ym', 'Yandex Market')], help_text='Маркетплейс', max_length=16)),
                ('token_name', models.CharField(help_text='Название токена (например statistics, analytics, orders_api)', max_length=64)),
                ('token_value', models.CharField(blank=True, default='', help_text='Значение токена', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли токен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_tokens', to='orders.partner')),
            ],
            options={
                'indexes': [models.Index(fields=['partner'], name='orders_part_partner_2ce56e_idx'), models.Index(fields=['partner', 'marketplace'], name='orders_part_partner_f4061c_idx'), models.Index(fields=['partner', 'marketplace', 'token_name'], name='orders_part_partner_c0e962_idx')],
            },
        ),
    ]
