# Generated by Django 5.2.11 on 2026-02-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_partnermarketplacetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(help_text='Название бренда (используется как ключ)', max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(help_text='Название категории (используется как ключ)', max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('wb_sku', models.CharField(help_text='Уникальный Артикул WB', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('seller_sku', models.CharField(help_text='Артикул продавца, Название товара', max_length=255)),
                ('brand', models.ForeignKey(help_text='Бренд товара', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.brand')),
                ('category', models.ForeignKey(help_text='Категория товара', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.category')),
                ('partner', models.ForeignKey(blank=True, help_text='Владелец товара (клиент или Business Unit ИП Никита Край)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='orders.partner')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('barcode', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('tech_size', models.CharField(max_length=255)),
                ('wb_size', models.CharField(max_length=255)),
                ('color', models.CharField(default='', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='orders.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('big', 'Big'), ('c246x328', 'C246x328'), ('c516x688', 'C516x688'), ('hq', 'HQ'), ('square', 'Square'), ('tm', 'TM')], max_length=20)),
                ('url', models.URLField()),
                ('local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='orders.product')),
            ],
            options={
                'unique_together': {('product', 'photo_type')},
            },
        ),
    ]
