# Generated by Django 5.2.11 on 2026-02-26 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_brand_category_product_productsku_productphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название планового товара (придуманное нами)', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Фото планового товара (если есть)', null=True, upload_to='planned_products/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи')),
                ('linked_product', models.OneToOneField(blank=True, help_text='Реальный товар, с которым связали данный плановый товар', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_match', to='orders.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('linked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.plannedproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan_product', 'product'), name='uniq_plan_product_product')],
            },
        ),
    ]
